SuperSandwich15000/Models/Commande.cs
namespace SuperSandwich15000.Models
{
    public class Commande
    {
        public int Id { get; set; }
        public int SandwichId { get; set; }
        public bool PainGris { get; set; }
        public string? Commentaire { get; set; }
        public string PourQui { get; set; }
        public DateTime Date { get; set; }
        public Sandwich sandwich;
    }
}

SuperSandwich15000/Models/ErrorViewModel.cs
namespace SuperSandwich15000.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperSandwich15000/Models/Sandwich.cs
using System.ComponentModel.DataAnnotations;

namespace SuperSandwich15000.Models
{
    public class Sandwich
    {
        
        public int Id { get; set; }

        [Required]
        [MaxLength(50)]
        public string Nom { get; set; }
        [Required]
        public decimal Prix { get; set; }

    }
}

SuperSandwich15000/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SuperSandwich15000.Models;
using System.Diagnostics;

namespace SuperSandwich15000.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperSandwich15000/Controllers/SandwichController.cs
using Microsoft.AspNetCore.Mvc;
using SuperSandwich15000.Models;
using SuperSandwich15000.Services;

namespace SuperSandwich15000.Controllers
{
    public class SandwichController : Controller
    {
        private SandwichService _sandwichService;
        private CommandeService _commandeService;
        
        public SandwichController()
        {
            _sandwichService = new SandwichService();
            _commandeService = new CommandeService();
        }
        public IActionResult Index()
        {
            return View(_sandwichService.GetAll());
        } 
        public IActionResult CreerCommande(int id)
        {
            Commande sandwichCommande = new Commande();
            sandwichCommande.SandwichId = id; 
            sandwichCommande.sandwich = _sandwichService.GetById(id) ;
            return View(sandwichCommande);
        }
        [HttpPost]
        public IActionResult CreerCommande(Commande commande) 
        {
            _commandeService.Create(commande);

            return RedirectToAction("Index");
        }
    }
}

SuperSandwich15000/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SuperSandwich15000/Views/Sandwich/CreerCommande.cshtml
@model SuperSandwich15000.Models.Commande

@{
    ViewData["Title"] = "CreerCommande";
}

<h1>CreerCommande</h1>

<h4>Vous êtes en train de commander : @Model.sandwich.Nom</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreerCommande">
            <div class="form-group" hidden>
                <label asp-for="SandwichId" class="control-label"></label>
                <input asp-for="SandwichId" class="form-control" />
                <span asp-validation-for="SandwichId" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PainGris"/> @Html.DisplayNameFor(model => model.PainGris)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Commentaire" class="control-label"></label>
                <input asp-for="Commentaire" class="form-control"/>
                <span asp-validation-for="Commentaire" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PourQui" class="control-label"></label>
                <input asp-for="PourQui" class="form-control"/>
                <span asp-validation-for="PourQui" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")"/>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

     

SuperSandwich15000/Views/Sandwich/Index.cshtml
@model IEnumerable<SuperSandwich15000.Models.Sandwich>

@{
    ViewData["Title"] = "Index";
}

<h1>Voici la liste des sandwichs</h1>
<img src="~/img/CarteSandwich.png" width="100%" />

    <div class="btn-group">
        <button type="button" class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Commande ton sandwich
        </button>
        <ul class="dropdown-menu">
            @foreach (Sandwich item in Model)
            {
                <li>
                    @Html.DisplayFor(modelItem => item.Nom)
                    @Html.DisplayFor(modelItem => item.Prix)
                <a type="button" class="btn btn-primary btn-sm" asp-controller="Sandwich" asp-action="CreerCommande" asp-route-id="@item.Id">Valider</a>
                </li>
            }
        </ul>
    </div>

 

SuperSandwich15000/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperSandwich15000</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SuperSandwich15000.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperSandwich15000</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sandwich" asp-action="Index">Liste des sandwichs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SuperSandwich15000 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>